name: Unikorn Push
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - name: Node Clean Install
        run: npm ci
      - name: ESLint
        run: npm run lint
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - name: Node Clean Install
        run: npm ci
      - name: Prettier Format
        run: npm run format
      - name: Formatted Checked In
        run: '[[ -z $(git status --porcelain) ]]'
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Images
        run: make images
